# Generated by Django 5.2.4 on 2025-07-22 15:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_propertybooking_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertybooking',
            name='slug',
        ),
        migrations.AddField(
            model_name='property',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertybooking',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='propertyreview',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
