# Generated by Django 5.2.4 on 2025-07-23 17:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_remove_propertybooking_slug_property_create_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertybooking',
            name='date_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='propertybooking',
            name='date_to',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
